[CR-999] Revert to pkg_resources instead of importlib for compatibility with py3.8
The earlier implementation was causing the following error:

```
Traceback (most recent call last):
  File "/home/pablo/.cache/pypoetry/virtualenvs/slamcore-utils-aDxSLirM-py3.8/bin/slamcore-convert-rosbag2", line 6, in <module>
    sys.exit(main())
  File "/home/pablo/Research/slamcore_utils-internal/slamcore_utils/scripts/convert_rosbag2.py", line 465, in main
    cast(Path, importlib.resources.path(__package__.split(".")[0], "ros2"))
TypeError: unsupported operand type(s) for /: '_GeneratorContextManager' and 'str'
```

Also allow running the script with our without the package properly
installed via pip or poetry